#if !defined (CTMP_PROJECT)
#define CTMP_PROJECT

#define BUILD_TARGET_NONE      0
#define BUILD_TARGET_TERMINAL  1
#define BUILD_TARGET_GRAPHICAL 2
#define BUILD_TARGET_SHARED    3

#define BUILD_OPTIMIZE_NONE    0
#define BUILD_OPTIMIZE_INSPECT 1
#define BUILD_OPTIMIZE_DEVELOP 2
#define BUILD_OPTIMIZE_RELEASE 3

#if !defined(BUILD_TARGET)
# define BUILD_TARGET BUILD_TARGET_NONE
#endif

#if !defined(BUILD_OPTIMIZE)
# define BUILD_OPTIMIZE BUILD_OPTIMIZE_NONE
#endif

#endif
