#if !defined (CTMP_PROJECT)
#define CTMP_PROJECT

#define BUILD_SUBSYSTEM_DEFAULT 0
#define BUILD_SUBSYSTEM_CONSOLE 1
#define BUILD_SUBSYSTEM_WINDOWS 2

#define BUILD_OPTIMIZE_DEFAULT 0
#define BUILD_OPTIMIZE_INSPECT 1
#define BUILD_OPTIMIZE_DEVELOP 2
#define BUILD_OPTIMIZE_RELEASE 3

#if !defined(BUILD_SUBSYSTEM)
# define BUILD_SUBSYSTEM BUILD_SUBSYSTEM_DEFAULT
#endif

#if !defined(BUILD_OPTIMIZE)
# define BUILD_OPTIMIZE BUILD_OPTIMIZE_DEFAULT
#endif

#endif
